# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('neighbourhood', models.CharField(choices=[('NRB', 'Nairobi'), ('KIS', 'Kisumu'), ('MBS', 'Mombasa'), ('MACH', 'Machakos'), ('KIT', 'Kitui')], max_length=20)),
                ('rating', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
